client_config_backend: settings
client_config:
  client_id: 545202917884-4gn999jog64bjlgnfe9oanvcr7j0pasp.apps.googleusercontent.com
  client_secret: _gqheY4OBdwfIbyHw6-0_tZd

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive.file
  - https://www.googleapis.com/auth/drive.install